# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "13e17fc272bbdba368eebb9b5a7d1d8e"
name = "hc-pricing-auto"
handle = "hc-pricing-auto"
application_url = "https://tuition-sodium-intellectual-olympics.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://tuition-sodium-intellectual-olympics.trycloudflare.com/auth/callback", "https://tuition-sodium-intellectual-olympics.trycloudflare.com/auth/shopify/callback", "https://tuition-sodium-intellectual-olympics.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
