# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "13e17fc272bbdba368eebb9b5a7d1d8e"
name = "hc-pricing-auto"
handle = "hc-pricing-auto"
application_url = "https://memory-rhythm-processing-promise.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled","inventory_levels/update"]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products, read_inventory, write_inventory"

[auth]
redirect_urls = ["https://memory-rhythm-processing-promise.trycloudflare.com/auth/callback", "https://memory-rhythm-processing-promise.trycloudflare.com/auth/shopify/callback", "https://memory-rhythm-processing-promise.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
